### ISSUE TITLE
SIP Plugin: Error setting ICE locally after SIP Busy here (486)

### ISSUE THREAD

**Issue by mtbramo** [meetecho/janus-gateway#1083]
Hi,
I'm using SIP plugin with release 0.2.5 and get error on new WebRTC call (same session and handle) after a SIP failure (in my case 486 Busy).
 The scenario is:
1) I perform a WebRTC call, sending "call" request to Janus, the initial offer is treated by ICE agent; An SIP INVITE is sent [nua_i_state]
2) I receive a response 486 Busy Here from SIP side, switch to [nua_i_state]: 486 Busy Here
3) I receive a 'hangup' event from Janus, but WebRTC client still continue to send 'trickle' candidate
4) Call status switch to 'idle' state.
5) Admin information is as follow:
        "registration_status": "registered",
        "call_status": "idle",
        "destroyed": 0
    },
    "flags": {
        "got-offer": true,
        "got-answer": true,
        "processing-offer": false,
        "starting": true,
        "ready": false,
        "stopped": false,
        "alert": true,
        "bundle": true,
        "rtcp-mux": true,
        "trickle": true,
        "all-trickles": false,
        "trickle-synced": false,
        "data-channels": false,
        "has-audio": true,
        "has-video": false,
        "plan-b": false,
        "cleaning": false
    },
    "sdps": {},
    "queued-packets": -1,
    "streams": []

6) Send a new 'call' request from WebRTC client and get a 490 Error setting ICE locally message:
Trace on Janus after offer:
[Wed Nov 22 15:31:43 2017] [126685401355855] Audio has been negotiated, Video has NOT been negotiated, SCTP/DataChannels have NOT been negotiated
[Wed Nov 22 15:31:43 2017] [126685401355855] The browser: supports BUNDLE, supports rtcp-mux, is doing Trickle ICE
[Wed Nov 22 15:31:43 2017] [WARN] [126685401355855] Agent already exists?
[Wed Nov 22 15:31:43 2017] [ERR] [janus.c:janus_process_incoming_request:1078] Error setting ICE locally
[Wed Nov 22 15:31:43 2017] [e0deece2-5713-454b-8a2b-2e7cfd6dfc8e_291] Returning Janus API error 490 (Error setting ICE locally)

NOTE: I have tried to send after 486 Busy response and new 'call' request, a 'hangup' request but like call status is already 'idle' nothing happen.

I doesn't know exactly what to do, except to recreate handle (detach/attach).

Thanks a lot for your job on Janus.

Regards,

   Eric.

**Comment by lminiero** [comment]
You should check what error you get on the console when it happens: "Error setting ICE locally" is a core error.

**Comment by mtbramo** [comment]
Lorenzo, 
My first idea was of course to send a "hangup" request to correcly release all the context, but when you do that after trickles (trickle not treated, still waiting for the answer), you get an error coming from SIP plugin (janus_sip_handler:2327) that say "Wrong state" (not in a call? status =idle).

 So even after the hangup, I get the same response "Error setting ICE locally". Call context is idle but not ICE one due to receipt of trickle after emission of SIP error.

The only solution that I found today is on error 490 to perform a detach/attach sequence and relaunch the register. But of course, user get a call failure on new "call" request after a SIP error and worst I think that he can't receive new call coming from SIP side (o verify).

I have associate the problem to a 486 Busy problem but of course the problem is the same whatever the error message that we receive from SIP side in response of INVITE.

Regards

**Comment by lminiero** [comment]
I'm talking core level hangup, not plugin level hangup.

**Comment by mtbramo** [comment]
Lorenzo,

I have not  seen that a "hangup" message exist; I will try it and tell you if all is OK.

Thanks

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/janus.c#L933 :wink:

**Comment by mtbramo** [comment]
Lorenzo,
I have sent a core "hangup", get a success but the result is the same.

I have checked the code and traces and see that even before calling core "hangup", we already perform a janus_ice_webrtc_hangup() operation (called from janus_plugin_close_pc).

Trace extract:

[Tue Nov 28 08:35:17 2017] [1023456][nua_i_state]: 0 INVITE sent
[Tue Nov 28 08:35:17 2017] [1023456][nua_r_invite]: 486 Busy Here
[Tue Nov 28 08:35:17 2017] [1023456][nua_i_state]: 486 Busy Here
[Tue Nov 28 08:35:17 2017] [6623487918275794] Sending event to transport...
[Tue Nov 28 08:35:17 2017] Sending event to janus.transport.websockets (0x7f91c0530360)
[Tue Nov 28 08:35:17 2017]   >> Pushing event: 0 (Success)
[Tue Nov 28 08:35:17 2017] [6623487918275794] Plugin asked to hangup PeerConnection: sending alert
[Tue Nov 28 08:35:17 2017] [6623487918275794] Telling the plugin about the hangup because of a Close PC (JANUS SIP plugin)
[Tue Nov 28 08:35:17 2017] No WebRTC media anymore
[Tue Nov 28 08:35:17 2017] [6623487918275794] Notifying WebRTC hangup
[Tue Nov 28 08:35:17 2017] [6623487918275794] Sending event to transport...
[Tue Nov 28 08:35:17 2017] Sending event to janus.transport.websockets (0x7f91c0530360)
[Tue Nov 28 08:35:17 2017] [1023456][nua_i_terminated]: 486 Busy Here
[Tue Nov 28 08:35:17 2017] [6623487918275794] ICE thread started
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0] Sending WebSocket message (117 bytes)...
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0]   -- Sent 117/117 bytes
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0] Sending WebSocket message (323 bytes)...
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0]   -- Sent 323/323 bytes
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0] Sending WebSocket message (382 bytes)...
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0]   -- Sent 382/382 bytes
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0] Sending WebSocket message (115 bytes)...
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0]   -- Sent 115/115 bytes
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0] Got 133 bytes:
[Tue Nov 28 08:35:17 2017] [WSS-0x7f91c00cc4d0] First fragment: 133 bytes, 0 remaining
[Tue Nov 28 08:35:17 2017] {"janus":"hangup","transaction":"dd18c522-eb7d-4506-88fa-4f9f821b918b_37","session_id":3654237131919762,"handle_id":6623487918275794}

Then, I get a success to hangup but as I relaunch a new call, I still get 490 error:


[Tue Nov 28 08:35:33 2017] Transport task pool, serving request
[Tue Nov 28 08:35:33 2017] [6623487918275794] There's a message for JANUS SIP plugin
[Tue Nov 28 08:35:33 2017] [6623487918275794] Still cleaning up from a previous media session, let's wait a bit...
[Tue Nov 28 08:35:36 2017] [6623487918275794]   -- Waited 3 seconds, that's enough!
[Tue Nov 28 08:35:36 2017] [6623487918275794] Remote SDP: ....

[Tue Nov 28 08:35:36 2017] [6623487918275794] Audio has been negotiated, Video has NOT been negotiated, SCTP/DataChannels have NOT been negotiated
[Tue Nov 28 08:35:36 2017] [6623487918275794] The browser: supports BUNDLE, supports rtcp-mux, is doing Trickle ICE
[Tue Nov 28 08:35:36 2017] [WARN] [6623487918275794] Agent already exists?
[Tue Nov 28 08:35:36 2017] [ERR] [janus.c:janus_process_incoming_request:1078] Error setting ICE locally
[Tue Nov 28 08:35:36 2017] [dd18c522-eb7d-4506-88fa-4f9f821b918b_38] Returning Janus API error 490 (Error setting ICE locally)


Regards

**Comment by lminiero** [comment]
Please stop posting logs inline: use pastebin/gist for that.

I do see that quite some time passes in between attempts (~16s). My guess is that there is some issue with cleaning up when the PC is only half set: in fact, in your case the remote peer sends the offer, and then it is hung up before an answer is received (the 486 means no offer will ever arrive). As a result, the state for the WebRTC stuff in the handle is stuck in "cleaning", never allowing you to go on.

We'll have a look to see if we can replicate the issue, and possibly work on a fix. As a side note, can you check if master or PR #1089 improves things for you? The latter is a set of improvements on the refcount branch, and not the older version of Janus you're using, but if that works for you it might mean we fixed it collaterally.

**Comment by lminiero** [comment]
You can also try PR #1035 which is similar to 1089 but with fixes for master instead.

**Comment by mtbramo** [comment]
Lorenzo,
Sorry for the late, I just tried the branch master this morning (Latest commit 0cfe923) and seen that the behaviour has changed; I now get an error code '471' ("still cleaning a previous session) on trickle request. 
I then tried to perform a core 'hangup' request, then launched a new call with called user in 'idle' state but still get 471 response. ICE handle context seem still in bad state.

Regards.

**Comment by atoppi** [comment]
@mtbramo looking into this, this is a race condition happening when a hangup coming from SIP 486 immediately follows a connection setup on the WebRTC side.

**Comment by mtbramo** [comment]
Yes, I understand that it's a race condition but is it possible to release the ICE context and continue to use the same session, handle  to perform a new successful call.

Or Do I have to detach/attach (create new handle), then register before performing new call.

**Comment by atoppi** [comment]
@mtbramo we are working on a fix, a PC should be re-usable after a busy response.
Detaching the handle is just a temporary workaround for your application.

**Comment by lminiero** [comment]
@mtbramo it's definitely possible, we do this all the time. Whether it's because of an incoming DTLS alert, or an explicit indication, a PeerConnection can be torn down, and after that you should be able to recreate another on the same handle. Notice that in master you'll have to wait a bit before you can re-create it, due to some garbage collection timing (usually about 1-2s): if you try too soon, you encounter the problem anyway, as you didn't give the core enough time to cleanup.

If this is not your case, and the ICE stack is apparently still there many seconds later, you may want to have a look at what the [Admin API](http://www.meetecho.com/blog/understanding-the-janus-admin-api/) returns for that handle, especially with respect to flags and stuff like that.

**Comment by mtbramo** [comment]
Thanks for your great job

**Comment by lminiero** [comment]
@mtbramo can you check if this latest commit fixes it for you? It seems to fix the issue in my setup, where I was indeed able to replicate the problem. @atoppi has an additional fix for some other race conditions that may occur, but I wanted to check if this simple change helps already.

**Comment by lminiero** [comment]
Any update?

**Comment by mtbramo** [comment]
Lorenzo,
It seems OK, I get the 486 Busy Here, then trickle are rejected with code 471 "Still cleaning a previous session". New call is correctly treated (same handle) without any action (core hangup or detach/attach operation).
Thanks.

**Comment by lminiero** [comment]
Ack, closing then.
