### ISSUE TITLE
Multistream segmentation fault

### ISSUE THREAD

**Issue by thatsmydoing** [meetecho/janus-gateway#2801]
This happens in `multistream` commit https://github.com/meetecho/janus-gateway/commit/17e5a46fc5ba371155143fcecc6225d154efc069

To reproduce, in mvideoroomtest.html, connect 2 clients and then unpublish one. This immediately crashes for me.

[AddressSanitizer stack trace](https://gist.github.com/thatsmydoing/1271755ac219f0f6a2968ab1db72da82)

**Comment by lminiero** [comment]
Good catch, it's probably because of changes we recently merged, the above commit should fix it.

**Comment by dewebdes** [comment]
There is some **bugs** about **UNPUBLISH** in **multistream live demo** remain:
https://github.com/meetecho/janus-gateway/blob/multistream/html/mvideoroomtest.html
The problem is for above link
After "Stop" button click and janus destroy but the local stream is still remain alive and webcam is in use by program
I try many many ways to stop the local track streams, like:

var vidTrack = myPluginHandle.webrtcStuff.myStream.getVideoTracks();
vidTrack.forEach(track => track.enabled = false);
vidTrack.forEach(track => track.stop());

But cant fix the problem, I used the multistream version because its ok in all devices but master version have some issue in windows ...

In the online demo: https://janus.conf.meetecho.com/mvideoroomtest.html
After stop, the page was reload and in this way its ok and webcam be disconnected
but I dont want to reload the page after stop streaming

**Comment by lminiero** [comment]
Stop asking the same question over and over, even highjacking other posts, or you'll get banned.

**Comment by dewebdes** [comment]
**banned??!!**
This is ur reward for janus lovers?
I comment the issue here because its similar, and at this time if u check ur online demo u can see this
Then the problem about unpublishing in multistream is still exist
I can fix it with IFrame (allow="camera *;microphone *") but It's a pity
