### ISSUE TITLE
regression: dtls does not connect for chrome-published streams

### ISSUE THREAD

**Issue by ploxiln** [meetecho/janus-gateway#329]
A version of janus from June 11 (11a33f5cad1d71ca396c6f8da02f813d9654b0f8) works with both firefox and chrome both publishing and viewing.

Current master seems to work with firefox publishing, firefox viewing, and chrome viewing, but not chrome publishing. I've determined this by testing with the videoroom plugin (and turning off "publish" for one side to make it uni-directional between two browsers).

Maybe related to #328?

Further details:

  * ubuntu 14.04
  * openssl-1.0.2d
  * libsrtp-1.5.2
  * sofia-sip-1.12.11
  * direct connection possible between browsers on 172.30.1.1 and janus on 172.30.1.2
  * janus log: https://gist.github.com/ploxiln/88dc0a32dd6fdf5a486a

key log lines (these two identical lines emitted together, every 20 seconds or so)
```
[WARN] [4287276313] Still waiting for the DTLS stack for component 1 in stream 1...
[WARN] [4287276313] Still waiting for the DTLS stack for component 1 in stream 1...
```

This state persists indefinitely. Janus admin says this (sdp trimmed):
```
{
    "session_id": 3447375110,
    "handle_id": 4287276313,
    "current_time": 20794988550,
    "plugin": "janus.plugin.videoroom",
    "plugin_specific": {
        "type": "publisher",
        "room": 1234,
        "id": 1679004654,
        "display": "usr1",
        "media": {
            "audio": 1,
            "video": 1,
            "data": 0
        },
        "destroyed": 0
    },
    "flags": {
        "got-offer": 1,
        "got-answer": 1,
        "processing-offer": 0,
        "starting": 1,
        "ready": 0,
        "stopped": 0,
        "alert": 0,
        "bundle": 1,
        "rtcp-mux": 1,
        "trickle": 1,
        "all-trickles": 1,
        "trickle-synced": 0,
        "data-channels": 0,
        "has-audio": 1,
        "has-video": 1,
        "plan-b": 0,
        "cleaning": 0
    },
    "agent-created": 20531834105,
    "ice-mode": "full",
    "ice-role": "controlled",
    "sdps": {
        "local": "v=0\r\no=- 20531862462 20531862461 IN IP4 127.0.0.1\r\ns=Demo Room\r\n...",
        "remote": "v=0\r\no=- 3285441602913217416 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\n..."
    },
    "streams": [
        {
            "id": 1,
            "ready": -1,
            "disabled": "false",
            "ssrc": {
                "audio": 4238369273,
                "video": 1848915221,
                "audio-peer": 4088070471,
                "video-peer": 1675023640,
                "video-peer-rtx": 1010825809
            },
            "components": [
                {
                    "id": 1,
                    "state": "connected",
                    "local-candidates": [
                        "1 1 udp 2013266431 172.30.1.2 10000 typ host\r\n",
                        "2 1 udp 2013266431 172.30.1.2 10000 typ host\r\n",
                        "3 1 udp 1677721855 108.176.27.194 62197 typ srflx raddr 10.0.2.15 rport 10000\r\n",
                        "4 1 udp 1845494015 192.168.41.119 52222 typ prflx raddr 10.0.2.15 rport 10000\r\n",
                        "5 1 udp 1677721855 108.176.27.194 6857 typ srflx raddr 172.30.1.2 rport 10000\r\n",
                        "6 1 udp 1845494015 192.168.41.119 61394 typ prflx raddr 172.30.1.2 rport 10000\r\n"
                    ],
                    "remote-candidates": [
                        "150719247 1 udp 2122260223 172.30.1.1 52605 typ host generation 0",
                        "2368367442 1 udp 2122194687 192.168.41.119 56509 typ host generation 0",
                        "150719247 1 udp 2122260223 172.30.1.1 50040 typ host generation 0",
                        "2368367442 1 udp 2122194687 192.168.41.119 58816 typ host generation 0",
                        "1101485249 1 udp 1685987071 108.176.27.194 1972 typ srflx raddr 192.168.41.119 rport 56509 generation 0",
                        "1101485249 1 udp 1685987071 108.176.27.194 4279 typ srflx raddr 192.168.41.119 rport 58816 generation 0"
                    ],
                    "dtls": {},
                    "in_stats": {},
                    "out_stats": {}
                }
            ]
        }
    ]
}
```

**Comment by ploxiln** [comment]
probably worth mentioning, echotest also suffers from this problem, but videoroom is closer to my actual usecase and maybe a simpler scenario

I may try to bisect (binary search git history) for the problematic change, tomorrow.

**Comment by lminiero** [comment]
I'm not aware of any such issue, we use git head regularly on several servers here and it works fine. Are you getting the same issue using the demos on janus.conf.meetecho.com as well?

I don't think your problem is #328, that's for incoming calls only and only happens with the SIP plugin when you vave the video m-line before audio, I think. I thought it might be related to #327 but I see all candidates there, so it's likely not that (you would be missing key candidates in that case).

From what I can see ICE seems to be working (```connected```) but there's no DTLS stack, probably because there never came the trigger to set it up: a failure in DTLS would still fill the ```dtls:{}``` section with info. As a matter of fact, I see no candidate pair selected, which is what we use as a trigger for that. Maybe because it never gets to ```"ready"```?

https://github.com/meetecho/janus-gateway/blob/master/ice.c#L1120
https://github.com/meetecho/janus-gateway/blob/master/ice.c#L1224

**Comment by lminiero** [comment]
As a side note, are you using 1024 certificates? Chrome won't accept any less than that I think, and we modified the stock certificates to account for that.

**Comment by ploxiln** [comment]
janus.conf.meetecho.com does seem to work. And I haven't yet tested my builds on a remote server such that the browser is behind a NAT.

The same 1024-bit certificate (which I generated myself), and janus config, and all libraries, is the same for the june-11 build and the current-master build which I am testing. Current Chrome does work with this setup with the june-11 build. The build behavior is reproducible; I've switched back and forth a few times with git checkout, git clean -fxd, ./autogen.sh, ./configure ..., make, sudo make install. You get the idea. The only variable different is the janus commit.

This is one of those things where a butterfly flaps its wings in Australia and webrtc ice/dtls just doesn't finish in NYC, and it's not the direct fault of any one piece of the complex system. Thanks for reading the logs and seeing if there was anything interesting there which I didn't pick up, I do appreciate it.

**Comment by ploxiln** [comment]
I ran a git bisect, it worked, and picked out a commit which seems plausible:

commit cc9eb176c5b8e08a4af2b174cafb9083d488f11e
Author: meetecho <github@meetecho.com>
Date:   Sat Jul 18 13:27:37 2015 +0200

    Fixed ICE not starting when all trickles received before processing remote answer

**Comment by ploxiln** [comment]
Also, reverting that commit on top of latest master, also fixes this for me.

**Comment by lminiero** [comment]
That's not a commit I can remove, I'm afraid, as it fixes a long time bug that affected Janus from time to time, especially when wrapping calls on the server side. Specifically, sometimes you could end up wit ICE never starting. This drove me crazy for a few months, and when I found a way to 100% replicate the problem I eventually fixed that with that patch.

Not sure why it's causing the issue for you, as ICE is indeed working in your case, it's just not switching to the ready state. Rather than reverting that commit, I'd like to understand what in it is breaking it for you. Have you checked if #330 helps?

**Comment by ploxiln** [comment]
I don't expect you to revert cc9eb17, I understand it does fix some things.

Unfortunately, no, #330 doesn't seem to change things, for my setup, with chrome.

**Comment by lminiero** [comment]
Can you check if adding an ```if(!janus_flags_is_set(&handle->webrtc_flags, JANUS_ICE_HANDLE_WEBRTC_START))``` to this ```else``` here:

https://github.com/meetecho/janus-gateway/blob/master/janus.c#L1512

helps? I'm wondering if the issue in your case is trying to start ICE twice, after maybe it has already been done before.

**Comment by ploxiln** [comment]
nope, sorry, same behavior

```
No more remote candidates for handle 3459771037!
[WARN] [3459771037] Still waiting for the DTLS stack for component 1 in stream 1...
[WARN] [3459771037] Still waiting for the DTLS stack for component 1 in stream 1...
```

(btw why does it complain about the same component/stream twice at once?)

**Comment by lminiero** [comment]
> (btw why does it complain about the same component/stream twice at once?)

It will print it for each packet received on that component before it is ready. My guess is the browser sent you a couple of DTLS messages in a row, probably as per the exponential backoff DTLS retransmissions are based upon. This makes me wonder if it might mean everything is fine on the browser side, though: have you checked with chrome://webrtc-internals the state of the PeerConnection, especially in regard to the ICE events?

**Comment by lminiero** [comment]
As a side note, I can't recall if I told you about this already, but I'd try and add ```172.``` to the ICE ignore list. Those addresses are, AFAIK, only used for inter-Docker communication, and you do have another private address that I guess is the one used to talk to the outside:

    <snip>
    [4287276313] Adding 10.0.2.15 to the addresses to gather candidates for
    [4287276313] Adding 172.30.1.2 to the addresses to gather candidates for
    <snip>

which means host and STUN addresses will still succeed using the ```10.``` one. We always ignore the ```172.``` addresses on our docker-based Janus servers, and I do know of another person who fixed their Janus connectivity issues by adding that to their own ignore list.

**Comment by lminiero** [comment]
If that still doesn't help, can you get a log with libnice debugging enabled?

**Comment by ploxiln** [comment]
Sure, I'll get some more logging, in the next day or so.

Actually, 172.30.1.0/24 is the subnet which both my host and my virtual machine is on, and that's how they talk to each other. the 10.0.0.0/16 subnet is virtualbox-application-nat, the host doesn't have an ip on that subnet, and can't reach that address directly. Docker uses 172.17.0.0/16 for containers that have their own network namespace / IP, but I use --net=host for all containers, so it's unused.

**Comment by ploxiln** [comment]
janus_chrome_fail_huge.log https://gist.github.com/ploxiln/c757415b37a1dfee2a3e
janus_firefox_success_huge.log https://gist.github.com/ploxiln/7a4ab8990ffddd0ec755

**Comment by ploxiln** [comment]
Better logs:
janus_chrome_fail_medium.log https://gist.github.com/ploxiln/644d0be9cff697050d0f
janus_firefox_success_medium.log https://gist.github.com/ploxiln/e21bd669c2e888341c70

**Comment by ploxiln** [comment]
Also worth mentioning, it works with the exact same build / config, if running on an ec2 host (so there's a 1-to-1 nat on the ec2 side and a home-router nat on the client side, instead of no nat anywhere as in the case that's failing here).

**Comment by lminiero** [comment]
I'm wondering if the cause is the prflx candidates: I don't think they're gathered, usually, but discovered while checking. This may be happening for how the interfaces are organized in your setup, ```10.``` being the VirtualBox host.

If you remember, some time ago there was a similar issue with prflx candidates confusing Chrome when using the public IP overwriting on 1-1 NATs, something that was fixed with STUN. Try skipping them here when adding candidates to the SDP:

https://github.com/meetecho/janus-gateway/blob/master/ice.c#L1938

with a ```nice_candidate_free(c); continue;```.

As a further test (maybe a separate one, not to mix results) you may also try to add the ```10.``` interface to the ignore list if ```172.``` is the one you're actually using.

**Comment by ploxiln** [comment]
I'm trying tests with every combination, but here's an interesting early result: if I remove the stun server from janus' config, the non-working-case works. (Client side aka browser can either use a stun server or no stun server.)

**Comment by ploxiln** [comment]
So, with this commit present, just considering stun server configuration, we're in a funny situation:

For Chrome, stun server is not needed on either janus side or client side, in either janus/client topology I test (in ec2 behind 1-to-1 NAT and normal home NAT, or in a VM with direct connection and no NAT).

But if a stun server is configured on the janus side, it makes chrome not work in the VM-no-NAT case.

But if a stun server is not configured on the janus side, it makes firefox not work in the ec2-1-to-1-plus-home-nat case. (Similar to chrome case but a bit different, doesn't say "Still waiting for DTLS" and actually fails after a while)

But all other combinations of firefox or chrome, stun server present or missing on client side, stun server present or missing on server side, client behind NAT or not, work.

OK I'll leave off the stun server and test with the code change and the interface enable/disable you suggest.

**Comment by ploxiln** [comment]
When ignoring the 10.0.* ip / iface, it still doesn't work. Here's the interesting part of the janus admin info as evidence:

```
            "components": [
                {
                    "id": 1,
                    "state": "connected",
                    "local-candidates": [
                        "1 1 udp 2013266431 172.30.1.2 10000 typ host\r\n",
                        "2 1 udp 1845494015 192.168.1.64 61791 typ prflx raddr 172.30.1.2 rport 10000\r\n",
                        "3 1 udp 1677721855 98.7.29.101 61791 typ srflx raddr 172.30.1.2 rport 10000\r\n"
                    ],
                    "remote-candidates": [
                        "150719247 1 udp 2122260223 172.30.1.1 55909 typ host generation 0",
                        "3460887983 1 udp 2122194687 192.168.1.64 51666 typ host generation 0",
                        "150719247 1 udp 2122260223 172.30.1.1 62682 typ host generation 0",
                        "3460887983 1 udp 2122194687 192.168.1.64 59188 typ host generation 0",
                        "945327227 1 udp 1685987071 98.7.29.101 51666 typ srflx raddr 192.168.1.64 rport 51666 generation 0",
                        "945327227 1 udp 1685987071 98.7.29.101 59188 typ srflx raddr 192.168.1.64 rport 59188 generation 0"
                    ],
                    "dtls": {},
```

Also interesting is that in this case, there's only one printout of `Still waiting for the DTLS stack for component 1 in stream 1...` at a time. So it's printing that message once per enabled network interface.

**Comment by ploxiln** [comment]
Hey, guess what, skipping peer reflexive candidates fixes this case, chrome <-> VM! You can laugh at me for trying this suggestion dead last. Anyway, *Diagnostic Success*.

**Comment by lminiero** [comment]
Multiple tests in different conditions are never useless :smile: 
So you mean that skipping prflx candidates fixes it for both Firefox and Chrome, with STUN server set and public_ip gone? If so, I can push a commit for that.

**Comment by ploxiln** [comment]
Yes, firefox was also working. No, was still using public_ip.

Currently our "production" janus instances (running in ec2) are running janus code about a week old but with the commit I bisected to reverted. They have the public_ip setting configured, as well as a stun server configured. The client application is currently configured to not use a stun server; its peer-reflexive candidate is used. Chrome, Firefox, and our android application, all seem to work with that configuration.

So that code change to fix peer-reflexive candidates, while "fixing" the VM case, would cause our current configuration in ec2 to break. I could of course re-enable use of STUN server on the client side, and that will *probably* work for all the configurations. But I'd rather not, I'll just stick with my patched branch for now. I just hope some of the test results are helpful.

**Comment by lminiero** [comment]
Not setting a STUN server on the client side and relying on prflx to get the host candidates to work, may indeed have it working, but I'm not sure it makes things faster. You'd need a connectivity check from the browser to Janus to start things, all the ones Janus would send before knowing the public address of the user would fail. Besides, it sounds a bit "dangerous", meaning I wouldn't feel 100% safe it would always work, but that's me.

Client side apart, I think that disabling public_ip in Janus and setting STUN there should get you the same result. You don't even need to reach a STUN server on the internet: you might deploy a STUN server on the same machine as Janus, and have it configured to return the machine public address for instance. This way STUN delays for Janus wouldn't be an issue.

**Comment by lminiero** [comment]
What about TURN, by the way? Are you gathering relay candidates on the client side?

**Comment by ploxiln** [comment]
Nope, no TURN either. If a browser (client) can communicate with a TURN server, it can communicate with janus with the prflx candidate. If it really can't use the prflx candidate to get responses from janus, it can't get anything from the TURN server either. It's the same principle: client sends UDP to the server, server sees what ip+port is in the ip header sender fields, and replies right back to that ip+port.

On the janus (server) side, the STUN server adds the srflx candidate in addition to the host candidate, when only the host candidate is needed on the janus (server) side. So it's double the candidates there.

I have noticed faster webrtc initialization with no ice servers on the client side, perhaps a half second instead of a full second. The other benefit to me is shorter log files and shorter lists of candidates in webrtc debug pages. On the browser (client) side there are more network interfaces and no interfaces are ignored, so a STUN server doubles what is already a long list of candidates. Seeing 15 trickle requests blurt out everywhere when a single webrtc connection is started kinda hurts, and does take some time.

For my use case where janus has a public ip and open udp ports, I don't see STUN and TURN as a "safety net" to increase reliability. They just mix the pseudorandom function of whether both sides will select a candidate and dtls will connect. (Yeah this is my new favorite metaphor for it.)

**Comment by lminiero** [comment]
TURN is still needed when port/transport filtering is in place.

Anyway, since this seems to be working for you, I'll update #341 and restore some way to force the public IP on candidates. I won't name it public IP, though, more something like "1-1 NAT public IP" or similar, and clarify the scenarios when it should be used, to avoid other less ICE-aware people misusing it and then complain things don't work.

**Comment by ploxiln** [comment]
Right. But we don't support TCP anyway. Because we don't use libnice > 0.1.4 because of #154. So TURN would not do anything for us at the present moment :)

**Comment by lminiero** [comment]
TCP would be used on the client side, not the server's. TURN only acts as a relay on the side that needs help: on the other side it's still regular UDP, and as far as Janus is concerned it's like establishing a connectivity check with a peer on a public address.

**Comment by ploxiln** [comment]
Ah, I didn't know that bit, thanks.

**Comment by ploxiln** [comment]
I was a bit confused when you first instructed me to make that change to skip prflx candidates; I didn't realize that just applied to candidates in the SDP.

Anyway, that works in all situations I've tested. Thanks for working through this with me.

**Comment by lminiero** [comment]
No problem, thanks to you for the tests under different conditions, they're really helpful!
